#!/bin/bash

# Created by argbash-init v2.11.0
# ARG_POSITIONAL_SINGLE([old],[original label volume])
# ARG_POSITIONAL_SINGLE([new],[new label volume to diff against old])
# ARG_POSITIONAL_SINGLE([output],[output diff volume (time-stacked per-label diffs)])
# ARG_HELP([Compute a per-label diff between two MINC label volumes.])
# ARGBASH_GO()
# needed because of Argbash --> m4_ignore([
### START OF CODE GENERATED BY Argbash v2.11.0 one line above ###
# Argbash is a bash code generator used to get arguments parsing right.
# Argbash is FREE SOFTWARE, see https://argbash.dev for more info


die()
{
	local _ret="${2:-1}"
	test "${_PRINT_HELP:-no}" = yes && print_help >&2
	echo "$1" >&2
	exit "${_ret}"
}


begins_with_short_option()
{
	local first_option all_short_options='h'
	first_option="${1:0:1}"
	test "$all_short_options" = "${all_short_options/$first_option/}" && return 1 || return 0
}

# THE DEFAULTS INITIALIZATION - POSITIONALS
_positionals=()
# THE DEFAULTS INITIALIZATION - OPTIONALS


print_help()
{
	printf '%s\n' "Compute a per-label diff between two MINC label volumes."
	printf 'Usage: %s [-h|--help] <old> <new> <output>\n' "$(basename "$0")"
	printf '\t%s\n' "<old>: original label volume"
	printf '\t%s\n' "<new>: new label volume to diff against old"
	printf '\t%s\n' "<output>: output diff volume (time-stacked per-label diffs)"
	printf '\t%s\n' "-h, --help: Prints help"
}


parse_commandline()
{
	_positionals_count=0
	local _key
	while test $# -gt 0
	do
		_key="$1"
		case "$_key" in
			-h|--help)
				print_help
				exit 0
				;;
			-h*)
				print_help
				exit 0
				;;
			*)
				_last_positional="$1"
				_positionals+=("$_last_positional")
				_positionals_count=$((_positionals_count + 1))
				;;
		esac
		shift
	done
}


handle_passed_args_count()
{
	local _required_args_string="'old', 'new' and 'output'"
	test "${_positionals_count}" -ge 3 || _PRINT_HELP=yes die "FATAL ERROR: Not enough positional arguments - we require exactly 3 (namely: $_required_args_string), but got only ${_positionals_count}." 1
	test "${_positionals_count}" -le 3 || _PRINT_HELP=yes die "FATAL ERROR: There were spurious positional arguments --- we expect exactly 3 (namely: $_required_args_string), but got ${_positionals_count} (the last one was: '${_last_positional}')." 1
}


assign_positional_args()
{
	local _positional_name _shift_for=$1
	_positional_names="_arg_old _arg_new _arg_output "

	shift "$_shift_for"
	for _positional_name in ${_positional_names}
	do
		test $# -gt 0 || break
		eval "$_positional_name=\${1}" || die "Error during argument parsing, possibly an Argbash bug." 1
		shift
	done
}

parse_commandline "$@"
handle_passed_args_count
assign_positional_args 1 "${_positionals[@]}"

# OTHER STUFF GENERATED BY Argbash

### END OF CODE GENERATED BY Argbash (sortof) ### ])
# [ <-- needed because of Argbash

set -euo pipefail

old=$_arg_old
new=$_arg_new
output=$_arg_output

# Preflight: required commands
for _dep in print_all_labels minclookup minccalc mincstats mincconcat; do
    command -v "$_dep" >/dev/null 2>&1 || { echo "Error: required command '$_dep' not found in PATH" >&2; exit 1; }
done

# Preflight: input files
[[ -e "$old" ]] || { echo "Error: input '$old' not found" >&2; exit 1; }
[[ -e "$new" ]] || { echo "Error: input '$new' not found" >&2; exit 1; }

tmpdir=$(mktemp -d)
trap 'rm -rf "${tmpdir}"' EXIT

oldlabels=$(print_all_labels "$old" | cut -d " " -f 2)
newlabels=$(print_all_labels "$new" | cut -d " " -f 2)
combinedlabels=$(echo ${oldlabels} ${newlabels} | tr ' ' '\n' | sort | uniq)

for label in ${oldlabels}; do
    minclookup -discrete -lut_string "$label 1" "$old" ${tmpdir}/${label}_old.mnc
done

for label in ${newlabels}; do
    minclookup -discrete -lut_string "$label 1" "$new" ${tmpdir}/${label}_new.mnc
done

changedlabels=""

for label in ${combinedlabels}; do
    if [[ ! -e ${tmpdir}/${label}_old.mnc ]]; then
        minccalc -expression 'A[0]?0:0' -byte -signed ${tmpdir}/${label}_new.mnc ${tmpdir}/${label}_old.mnc
    elif [[ ! -e ${tmpdir}/${label}_new.mnc ]]; then
        minccalc -expression 'A[0]?0:0' -byte -signed ${tmpdir}/${label}_old.mnc ${tmpdir}/${label}_new.mnc
    fi

    minccalc -labels -signed -byte -expression 'A[0] - A[1]' ${tmpdir}/${label}_new.mnc ${tmpdir}/${label}_old.mnc ${tmpdir}/${label}_diff.mnc

    # sum2 of {-1,0,1} diff data == count of changed voxels; numeric >0 test via awk
    sum2=$(mincstats -quiet -sum2 ${tmpdir}/${label}_diff.mnc)
    if awk -v s="$sum2" 'BEGIN{exit !(s>0)}'; then
        changedlabels+="${label} "
    else
        rm ${tmpdir}/${label}_diff.mnc
    fi
done

if [[ -z "${changedlabels// }" ]]; then
    echo "No label differences between ${old} and ${new}." >&2
    exit 0
fi

mincconcat -clobber -valid_range -1 1 -signed -byte -concat_dimension time \
    -coordlist "$(echo ${changedlabels} | tr ' ' '\n' | paste -s -d",")" \
    $(for label in ${changedlabels}; do echo -n "${tmpdir}/${label}_diff.mnc "; done) \
    "${output}"

# ] <-- needed because of Argbash
