#!/bin/bash
#Generate auto-scaled MaGeT QC image
#TODO
#-option for label on-off slices
#-option for number of slices
#-option for image size

# Created by argbash-init v2.11.0
# ARG_POSITIONAL_SINGLE([image],[background anatomical MINC volume])
# ARG_POSITIONAL_SINGLE([labels],[time-stacked label/diff MINC volume to visualize])
# ARG_POSITIONAL_SINGLE([output],[output image prefix (writes PREFIX_t.jpg, _s.jpg, _c.jpg)])
# ARG_HELP([Generate auto-scaled QC images (t/s/c planes) for a time-stacked label volume.])
# ARGBASH_GO()
# needed because of Argbash --> m4_ignore([
### START OF CODE GENERATED BY Argbash v2.11.0 one line above ###
# Argbash is a bash code generator used to get arguments parsing right.
# Argbash is FREE SOFTWARE, see https://argbash.dev for more info


die()
{
	local _ret="${2:-1}"
	test "${_PRINT_HELP:-no}" = yes && print_help >&2
	echo "$1" >&2
	exit "${_ret}"
}


begins_with_short_option()
{
	local first_option all_short_options='h'
	first_option="${1:0:1}"
	test "$all_short_options" = "${all_short_options/$first_option/}" && return 1 || return 0
}

# THE DEFAULTS INITIALIZATION - POSITIONALS
_positionals=()
# THE DEFAULTS INITIALIZATION - OPTIONALS


print_help()
{
	printf '%s\n' "Generate auto-scaled QC images (t/s/c planes) for a time-stacked label volume."
	printf 'Usage: %s [-h|--help] <image> <labels> <output>\n' "$(basename "$0")"
	printf '\t%s\n' "<image>: background anatomical MINC volume"
	printf '\t%s\n' "<labels>: time-stacked label/diff MINC volume to visualize"
	printf '\t%s\n' "<output>: output image prefix (writes PREFIX_t.jpg, _s.jpg, _c.jpg)"
	printf '\t%s\n' "-h, --help: Prints help"
}


parse_commandline()
{
	_positionals_count=0
	local _key
	while test $# -gt 0
	do
		_key="$1"
		case "$_key" in
			-h|--help)
				print_help
				exit 0
				;;
			-h*)
				print_help
				exit 0
				;;
			*)
				_last_positional="$1"
				_positionals+=("$_last_positional")
				_positionals_count=$((_positionals_count + 1))
				;;
		esac
		shift
	done
}


handle_passed_args_count()
{
	local _required_args_string="'image', 'labels' and 'output'"
	test "${_positionals_count}" -ge 3 || _PRINT_HELP=yes die "FATAL ERROR: Not enough positional arguments - we require exactly 3 (namely: $_required_args_string), but got only ${_positionals_count}." 1
	test "${_positionals_count}" -le 3 || _PRINT_HELP=yes die "FATAL ERROR: There were spurious positional arguments --- we expect exactly 3 (namely: $_required_args_string), but got ${_positionals_count} (the last one was: '${_last_positional}')." 1
}


assign_positional_args()
{
	local _positional_name _shift_for=$1
	_positional_names="_arg_image _arg_labels _arg_output "

	shift "$_shift_for"
	for _positional_name in ${_positional_names}
	do
		test $# -gt 0 || break
		eval "$_positional_name=\${1}" || die "Error during argument parsing, possibly an Argbash bug." 1
		shift
	done
}

parse_commandline "$@"
handle_passed_args_count
assign_positional_args 1 "${_positionals[@]}"

# OTHER STUFF GENERATED BY Argbash

### END OF CODE GENERATED BY Argbash (sortof) ### ])
# [ <-- needed because of Argbash

set -euo pipefail

image=$_arg_image
labels=$_arg_labels
output=$_arg_output

# Preflight: required commands
for _dep in mincinfo mincreshape minclookup mincmath mincresample mincbbox minccalc create_verify_image parallel convert nproc; do
    command -v "$_dep" >/dev/null 2>&1 || { echo "Error: required command '$_dep' not found in PATH" >&2; exit 1; }
done

# Preflight: input files
[[ -e "$image" ]] || { echo "Error: input '$image' not found" >&2; exit 1; }
[[ -e "$labels" ]] || { echo "Error: input '$labels' not found" >&2; exit 1; }

tmpdir=$(mktemp -d)
trap 'rm -rf "${tmpdir}"' EXIT

patchlabels=$(mincinfo -varvalues time ${labels})

i=0
for label in ${patchlabels}; do
    echo "mincreshape -valid_range -1 1 ${labels} ${tmpdir}/${label}_patch.mnc -dimrange time=${i} -signed -byte && \
         minclookup -byte -unsigned -labels -discrete -lut_string \"-1 2; 1 1\" ${tmpdir}/${label}_patch.mnc ${tmpdir}/${label}_patch_fix.mnc"
    # Generate an empty file if not present in existing label set so we can patch it
    ((i++)) || true
done | parallel -j $(nproc)

# Generate a bounding box; -or needs >=2 inputs, so copy through when only one
fixfiles=(${tmpdir}/*_patch_fix.mnc)
if (( ${#fixfiles[@]} == 1 )); then
    cp "${fixfiles[0]}" ${tmpdir}/label_flatten.mnc
else
    mincmath -or "${fixfiles[@]}" ${tmpdir}/label_flatten.mnc
fi
mincresample -unsigned -int -keep -near -labels $(mincbbox -mincresample ${tmpdir}/label_flatten.mnc | grep -v Reading) \
    ${tmpdir}/label_flatten.mnc ${tmpdir}/label-crop.mnc
minccalc -expression "1" ${tmpdir}/label-crop.mnc ${tmpdir}/bounding.mnc

# Labelled layers
for label in ${patchlabels}; do
echo """
create_verify_image -transpose  -range_floor 0 ${tmpdir}/$(basename ${image} .mnc)_t_${label}.mpc \
    -width 3840 -height 1600 -autocols 10 -autocol_planes t \
    -bounding_volume ${tmpdir}/bounding.mnc \
    -row ${image} color:gray \
    volume_overlay:${tmpdir}/${label}_patch_fix.mnc:0.7:2:blue,1:red \
    title:\"Label ${label}\" \
    -norepeattitle


create_verify_image -transpose  -range_floor 0 ${tmpdir}/$(basename ${image} .mnc)_s_${label}.mpc \
    -width 3840 -height 1600 -autocols 10 -autocol_planes s \
    -bounding_volume ${tmpdir}/bounding.mnc \
    -row ${image} color:gray \
    volume_overlay:${tmpdir}/${label}_patch_fix.mnc:0.7:2:blue,1:red \
    title:\"Label ${label}\" \
    -norepeattitle

create_verify_image -transpose  -range_floor 0 ${tmpdir}/$(basename ${image} .mnc)_c_${label}.mpc \
    -width 3840 -height 1600 -autocols 10 -autocol_planes c \
    -bounding_volume ${tmpdir}/bounding.mnc \
    -row ${image} color:gray \
    volume_overlay:${tmpdir}/${label}_patch_fix.mnc:0.7:2:blue,1:red \
    title:\"Label ${label}\" \
    -norepeattitle
"""
done | parallel -j $(nproc)

convert -background black -strip -interlace Plane -sampling-factor 4:2:0 -quality "95%"  \
    +append -trim \
    $(for label in ${patchlabels}; do echo ${tmpdir}/$(basename ${image} .mnc)_t_${label}.mpc; done) \
    ${output}_t.jpg

convert -background black -strip -interlace Plane -sampling-factor 4:2:0 -quality "95%"  \
    +append -trim \
    $(for label in ${patchlabels}; do echo ${tmpdir}/$(basename ${image} .mnc)_s_${label}.mpc; done) \
    ${output}_s.jpg

convert -background black -strip -interlace Plane -sampling-factor 4:2:0 -quality "95%"  \
    +append -trim \
    $(for label in ${patchlabels}; do echo ${tmpdir}/$(basename ${image} .mnc)_c_${label}.mpc; done) \
    ${output}_c.jpg

# ] <-- needed because of Argbash
