#!/bin/bash

# Created by argbash-init v2.11.0
# ARG_POSITIONAL_SINGLE([old],[original label volume to patch])
# ARG_POSITIONAL_SINGLE([patch],[diff volume produced by diff-labels.sh])
# ARG_POSITIONAL_SINGLE([output],[output patched label volume])
# ARG_HELP([Apply a time-stacked label diff to a MINC label volume.])
# ARGBASH_GO()
# needed because of Argbash --> m4_ignore([
### START OF CODE GENERATED BY Argbash v2.11.0 one line above ###
# Argbash is a bash code generator used to get arguments parsing right.
# Argbash is FREE SOFTWARE, see https://argbash.dev for more info


die()
{
	local _ret="${2:-1}"
	test "${_PRINT_HELP:-no}" = yes && print_help >&2
	echo "$1" >&2
	exit "${_ret}"
}


begins_with_short_option()
{
	local first_option all_short_options='h'
	first_option="${1:0:1}"
	test "$all_short_options" = "${all_short_options/$first_option/}" && return 1 || return 0
}

# THE DEFAULTS INITIALIZATION - POSITIONALS
_positionals=()
# THE DEFAULTS INITIALIZATION - OPTIONALS


print_help()
{
	printf '%s\n' "Apply a time-stacked label diff to a MINC label volume."
	printf 'Usage: %s [-h|--help] <old> <patch> <output>\n' "$(basename "$0")"
	printf '\t%s\n' "<old>: original label volume to patch"
	printf '\t%s\n' "<patch>: diff volume produced by diff-labels.sh"
	printf '\t%s\n' "<output>: output patched label volume"
	printf '\t%s\n' "-h, --help: Prints help"
}


parse_commandline()
{
	_positionals_count=0
	local _key
	while test $# -gt 0
	do
		_key="$1"
		case "$_key" in
			-h|--help)
				print_help
				exit 0
				;;
			-h*)
				print_help
				exit 0
				;;
			*)
				_last_positional="$1"
				_positionals+=("$_last_positional")
				_positionals_count=$((_positionals_count + 1))
				;;
		esac
		shift
	done
}


handle_passed_args_count()
{
	local _required_args_string="'old', 'patch' and 'output'"
	test "${_positionals_count}" -ge 3 || _PRINT_HELP=yes die "FATAL ERROR: Not enough positional arguments - we require exactly 3 (namely: $_required_args_string), but got only ${_positionals_count}." 1
	test "${_positionals_count}" -le 3 || _PRINT_HELP=yes die "FATAL ERROR: There were spurious positional arguments --- we expect exactly 3 (namely: $_required_args_string), but got ${_positionals_count} (the last one was: '${_last_positional}')." 1
}


assign_positional_args()
{
	local _positional_name _shift_for=$1
	_positional_names="_arg_old _arg_patch _arg_output "

	shift "$_shift_for"
	for _positional_name in ${_positional_names}
	do
		test $# -gt 0 || break
		eval "$_positional_name=\${1}" || die "Error during argument parsing, possibly an Argbash bug." 1
		shift
	done
}

parse_commandline "$@"
handle_passed_args_count
assign_positional_args 1 "${_positionals[@]}"

# OTHER STUFF GENERATED BY Argbash

### END OF CODE GENERATED BY Argbash (sortof) ### ])
# [ <-- needed because of Argbash

set -euo pipefail

old=$_arg_old
patch=$_arg_patch
output=$_arg_output

# Preflight: required commands
for _dep in print_all_labels mincinfo minclookup mincreshape minccalc mincstats mincmath; do
    command -v "$_dep" >/dev/null 2>&1 || { echo "Error: required command '$_dep' not found in PATH" >&2; exit 1; }
done

# Preflight: input files
[[ -e "$old" ]] || { echo "Error: input '$old' not found" >&2; exit 1; }
[[ -e "$patch" ]] || { echo "Error: input '$patch' not found" >&2; exit 1; }

tmpdir=$(mktemp -d)
trap 'rm -rf "${tmpdir}"' EXIT

oldlabels=$(print_all_labels ${old} | cut -d " " -f 2)
patchlabels=$(mincinfo -varvalues time ${patch})
combinedlabels=$(echo ${oldlabels} ${patchlabels} | tr ' ' '\n' | sort | uniq)

#Split up original label file
for label in ${oldlabels}; do
    minclookup -discrete -lut_string "$label 1" ${old} ${tmpdir}/${label}_old.mnc
done

#Split up patch set
i=0
for label in ${patchlabels}; do
    mincreshape -valid_range -1 1 ${patch} ${tmpdir}/${label}_patch.mnc -dimrange time=${i} -signed -byte
    #Generate an empty file if not present in existing label set so we can patch it
    ((i++)) || true
done

#Apply patch to labels, in the case of missing label or patch, skip patching
for label in ${combinedlabels}; do
    if [[ ! -e ${tmpdir}/${label}_old.mnc ]]; then
        if [[ $(mincstats -min -quiet ${tmpdir}/${label}_patch.mnc) == "-1" ]]; then
            echo "Warning, patch ${label} deletes voxels but no original label exists! Ignoring negative patches!"
        fi
        minccalc -labels -unsigned -byte -expression "A[0]>0?(A[0]*${label}):0" ${tmpdir}/${label}_patch.mnc ${tmpdir}/${label}_new.mnc
    elif [[ ! -e ${tmpdir}/${label}_patch.mnc ]]; then
        minccalc -labels -unsigned -byte -expression "A[0]*${label}" ${tmpdir}/${label}_old.mnc ${tmpdir}/${label}_new.mnc
    else
        minccalc -labels -unsigned -byte -expression "(A[0]+A[1])*${label}" ${tmpdir}/${label}_old.mnc ${tmpdir}/${label}_patch.mnc ${tmpdir}/${label}_new.mnc
    fi
done

# Merge per-label results; -add needs >=2 inputs, so copy through when only one
newfiles=(${tmpdir}/*_new.mnc)
if (( ${#newfiles[@]} == 1 )); then
    cp "${newfiles[0]}" "${output}"
else
    mincmath -clobber -labels -unsigned -byte -add "${newfiles[@]}" "${output}"
fi

# ] <-- needed because of Argbash
